In [2]:
import json
import pandas as pd

In [3]:
with open('../data_processed/dados_tratados.json', 'r') as file:
    data = json.load(file)

In [4]:
data_coordinates = []
data_properties = []

In [5]:
for record in data:
    data_coordinates.append(record['geometry'])
    data_properties.append(record['properties'])

In [6]:
df_cordenadas = pd.DataFrame(data_coordinates)
df_properties = pd.DataFrame(data_properties)
df_properties.head()

,collectioncode,catalognumber,scientificname,kingdom,family,genus,country,stateprovince,county,locality,...,maximumelevationinmeters,typestatus,recordnumber,infraspecificepithet,previouscatalognumber,sex,coordinateprecision,preparationtype,relatedcatalogitem,relationshiptype
0,DZSJRP-PISCES,20954,Nannostomus beckfordi,Animalia,Lebiasinidae,Nannostomus,Brasil,Alagoas,Marechal Deodoro,Riacho sem nome,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,G,G00162341,Averrhoidium gardnerianum,Plantae,Sapindaceae,Averrhoidium,Brazil,Alagoas,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DZSJRP-PISCES,21288,Hoplias brasiliensis,Animalia,Erythrinidae,Hoplias,Brasil,Alagoas,Satuba,"Riacho 16, CELMM, bacia do Rio Mundaú",...,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DZSJRP-PISCES,21211,Kryptolebias,Animalia,Rivulidae,Kryptolebias,Brasil,Alagoas,Marechal Deodoro,"Riacho 1, Complexo Estuarino Lagunar Mundaú-Ma...",...,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,G,G00227626,Campomanesia dichotoma,Plantae,Myrtaceae,Campomanesia,Brazil,Alagoas,NaN,NaN,...,NaN,ISOTYPUS of Britoa dichotoma O. Berg,1294,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_combined = pd.concat([df_cordenadas, df_properties], axis=1)
df_combined.head(2)

,type,coordinates,collectioncode,catalognumber,scientificname,kingdom,family,genus,country,stateprovince,...,maximumelevationinmeters,typestatus,recordnumber,infraspecificepithet,previouscatalognumber,sex,coordinateprecision,preparationtype,relatedcatalogitem,relationshiptype
0,Point,"-35.92175, -9.69358",DZSJRP-PISCES,20954,Nannostomus beckfordi,Animalia,Lebiasinidae,Nannostomus,Brasil,Alagoas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Point,"-36.69166667, -9.77361111",G,G00162341,Averrhoidium gardnerianum,Plantae,Sapindaceae,Averrhoidium,Brazil,Alagoas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_combined.columns

Index(['type', 'coordinates', 'collectioncode', 'catalognumber',
       'scientificname', 'kingdom', 'family', 'genus', 'country',
       'stateprovince', 'county', 'locality', 'institutioncode', 'phylum',
       'class', 'order', 'basisofrecord', 'fieldnumber', 'individualcount',
       'verbatimlatitude', 'verbatimlongitude', 'collectionid',
       'specificepithet', 'decimallongitude', 'decimallatitude', 'modified',
       'scientificnameauthorship', 'occurrenceremarks', 'datecollected',
       'barcode', 'continentocean', 'identifiedby', 'yearidentified',
       'monthidentified', 'dayidentified', 'recordedby',
       'minimumelevationinmeters', 'maximumelevationinmeters', 'typestatus',
       'recordnumber', 'infraspecificepithet', 'previouscatalognumber', 'sex',
       'coordinateprecision', 'preparationtype', 'relatedcatalogitem',
       'relationshiptype'],
      dtype='object')

In [9]:
colunas_vazias = df_combined.isnull().sum()
colunas_vazias_ordenadas = colunas_vazias.sort_values(ascending=False)

In [10]:
media = colunas_vazias_ordenadas.median()

colunas_remover = colunas_vazias_ordenadas[colunas_vazias_ordenadas > media].index
colunas_remover

Index(['relationshiptype', 'infraspecificepithet', 'previouscatalognumber',
       'typestatus', 'preparationtype', 'relatedcatalogitem',
       'minimumelevationinmeters', 'maximumelevationinmeters', 'fieldnumber',
       'sex', 'coordinateprecision', 'individualcount', 'dayidentified',
       'monthidentified', 'phylum', 'class', 'order', 'yearidentified',
       'continentocean', 'barcode', 'occurrenceremarks', 'identifiedby',
       'scientificnameauthorship'],
      dtype='object')

In [11]:
df_cleaned = df_combined.drop(columns=colunas_remover)

In [12]:
df_cleaned.columns

Index(['type', 'coordinates', 'collectioncode', 'catalognumber',
       'scientificname', 'kingdom', 'family', 'genus', 'country',
       'stateprovince', 'county', 'locality', 'institutioncode',
       'basisofrecord', 'verbatimlatitude', 'verbatimlongitude',
       'collectionid', 'specificepithet', 'decimallongitude',
       'decimallatitude', 'modified', 'datecollected', 'recordedby',
       'recordnumber'],
      dtype='object')

In [13]:
df_cleaned.to_csv('../data_processed/dados_tratados.csv', index=False)